DBT_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_DB
      schema: DBT_TARGET_SC
      account: 'RNGQJWH-BP88765'
      user: 'Pavi'
